name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.rust }} ${{ matrix.crate }} (${{ matrix.run }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, nightly ]
        crate: [cargo-all-features, "--git https://github.com/somehowchris/cargo-all-features.git"]
        run: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

    steps:
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - run: cargo install ${{ matrix.crate }}